failing test attempt

diff --git a/.github/workflows/pr_comment.yml b/.github/workflows/pr_comment.yml
--- a/.github/workflows/pr_comment.yml
+++ b/.github/workflows/pr_comment.yml
@@ -66,7 +66,8 @@ jobs:
 
       - name: Run test
         run: |
-          echo "Test succeeds"
+          echo "Test fails"
+          exit 1
       
       - name: Set final status
         if: always()
